<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN00439" name="com.ssp.regression.insurer.testscripts.US_6634" tests="2" failures="2" timestamp="2 Jan 2019 06:53:29 GMT" time="0.002" errors="0">
  <testcase name="TC_6634_6704_02" time="0.001" classname="com.ssp.regression.insurer.testscripts.US_6634"/>
  <testcase name="TC_6634_6704_01" time="0.001" classname="com.ssp.regression.insurer.testscripts.US_6634">
    <failure type="org.testng.SkipException" message="Hub is not started or down.">
      <![CDATA[org.testng.SkipException: Hub is not started or down.
	at com.ssp.support.WebDriverFactory.get(WebDriverFactory.java:334)
	at com.ssp.regression.insurer.testscripts.US_6634.TC_6634_6704_01(US_6634.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_6634_6704_01 -->
</testsuite> <!-- com.ssp.regression.insurer.testscripts.US_6634 -->
